Just do a full release build for the bench job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,6 +43,171 @@ jobs:
           GIT_MESSAGE=$(git log --format=%s -n 1 ${{github.event.after}})
           echo Commit message: $GIT_MESSAGE
           echo $GIT_MESSAGE | grep '\[ci\]' || (echo 'Exiting due to draft PR. Commit with [ci] to bypass or add the ci-draft label.' ; echo 'skip_build=true' >> $GITHUB_OUTPUT)
+  bench:
+    name: bench release linux-x86_64
+    needs:
+      - pre_build
+    if: needs.pre_build.outputs.skip_build != 'true'
+    runs-on: '${{ github.repository == ''denoland/deno'' && ''ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04'' || ''ubuntu-24.04'' }}'
+    timeout-minutes: 240
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Configure git
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        run: |-
+          git config --global core.symlinks true
+          git config --global fetch.parallel 32
+      - name: Clone repository
+        uses: actions/checkout@v6
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        with:
+          fetch-depth: 5
+          submodules: false
+      - name: Install Node
+        uses: actions/setup-node@v6
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        with:
+          node-version: 22
+      - uses: dsherret/rust-toolchain-file@v1
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+      - name: Cache Cargo home
+        uses: cirruslabs/cache@v4
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        with:
+          path: |-
+            ~/.cargo/.crates.toml
+            ~/.cargo/.crates2.json
+            ~/.cargo/bin
+            ~/.cargo/registry/index
+            ~/.cargo/registry/cache
+            ~/.cargo/git/db
+          key: '94-cargo-home-linux-x86_64-${{ hashFiles(''Cargo.lock'') }}'
+          restore-keys: 94-cargo-home-linux-x86_64-
+      - name: Clone submodule ./tests/bench/testdata/lsp_benchdata
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        run: git submodule update --init --recursive --depth=1 -- ./tests/bench/testdata/lsp_benchdata
+      - name: Clone submodule ./tests/util/std
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        run: git submodule update --init --recursive --depth=1 -- ./tests/util/std
+      - name: Set up incremental LTO and sysroot build
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        run: |-
+          # Setting up sysroot
+          export DEBIAN_FRONTEND=noninteractive
+          # Avoid running man-db triggers, which sometimes takes several minutes
+          # to complete.
+          sudo apt-get -qq remove --purge -y man-db > /dev/null 2> /dev/null
+          # Remove older clang before we install
+          sudo apt-get -qq remove   'clang-12*' 'clang-13*' 'clang-14*' 'clang-15*' 'clang-16*' 'clang-17*' 'clang-18*' 'clang-19*' 'llvm-12*' 'llvm-13*' 'llvm-14*' 'llvm-15*' 'llvm-16*' 'llvm-17*' 'llvm-18*' 'llvm-19*' 'lld-12*' 'lld-13*' 'lld-14*' 'lld-15*' 'lld-16*' 'lld-17*' 'lld-18*' 'lld-19*' > /dev/null 2> /dev/null
+
+          # Install clang-XXX, lld-XXX, and debootstrap.
+          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-21 main" |
+            sudo dd of=/etc/apt/sources.list.d/llvm-toolchain-jammy-21.list
+          curl https://apt.llvm.org/llvm-snapshot.gpg.key |
+            gpg --dearmor                                 |
+          sudo dd of=/etc/apt/trusted.gpg.d/llvm-snapshot.gpg
+          sudo apt-get update
+          # this was unreliable sometimes, so try again if it fails
+          sudo apt-get install -y --no-install-recommends clang-21 lld-21 clang-tools-21 clang-format-21 clang-tidy-21 || (echo 'Failed. Trying again.' && sudo apt-get clean && sudo apt-get update && sudo apt-get install -y --no-install-recommends clang-21 lld-21 clang-tools-21 clang-format-21 clang-tidy-21)
+          # Fix alternatives
+          (yes '' | sudo update-alternatives --force --all) > /dev/null 2> /dev/null || true
+
+          clang-21 -c -o /tmp/memfd_create_shim.o tools/memfd_create_shim.c -fPIC
+
+          echo "Decompressing sysroot..."
+          wget -q https://github.com/denoland/deno_sysroot_build/releases/download/sysroot-20250207/sysroot-`uname -m`.tar.xz -O /tmp/sysroot.tar.xz
+          cd /
+          xzcat /tmp/sysroot.tar.xz | sudo tar -x
+          sudo mount --rbind /dev /sysroot/dev
+          sudo mount --rbind /sys /sysroot/sys
+          sudo mount --rbind /home /sysroot/home
+          sudo mount -t proc /proc /sysroot/proc
+          cd
+
+          echo "Done."
+
+          # Configure the build environment. Both Rust and Clang will produce
+          # llvm bitcode only, so we can use lld's incremental LTO support.
+
+          # Load the sysroot's env vars
+          echo "sysroot env:"
+          cat /sysroot/.env
+          . /sysroot/.env
+
+          # Important notes:
+          #   1. -ldl seems to be required to avoid a failure in FFI tests. This flag seems
+          #      to be in the Rust default flags in the smoketest, so uncertain why we need
+          #      to be explicit here.
+          #   2. RUSTFLAGS and RUSTDOCFLAGS must be specified, otherwise the doctests fail
+          #      to build because the object formats are not compatible.
+          echo "
+          CARGO_PROFILE_BENCH_INCREMENTAL=false
+          CARGO_PROFILE_RELEASE_INCREMENTAL=false
+          RUSTFLAGS<<__1
+            -C linker-plugin-lto=true
+            -C linker=clang-21
+            -C link-arg=-fuse-ld=lld-21
+            -C link-arg=-ldl
+            -C link-arg=-Wl,--allow-shlib-undefined
+            -C link-arg=-Wl,--thinlto-cache-dir=$(pwd)/target/release/lto-cache
+            -C link-arg=-Wl,--thinlto-cache-policy,cache_size_bytes=700m
+            -C link-arg=/tmp/memfd_create_shim.o
+            --cfg tokio_unstable
+            $RUSTFLAGS
+          __1
+          RUSTDOCFLAGS<<__1
+            -C linker-plugin-lto=true
+            -C linker=clang-21
+            -C link-arg=-fuse-ld=lld-21
+            -C link-arg=-ldl
+            -C link-arg=-Wl,--allow-shlib-undefined
+            -C link-arg=-Wl,--thinlto-cache-dir=$(pwd)/target/release/lto-cache
+            -C link-arg=-Wl,--thinlto-cache-policy,cache_size_bytes=700m
+            -C link-arg=/tmp/memfd_create_shim.o
+            --cfg tokio_unstable
+            $RUSTFLAGS
+          __1
+          CC=/usr/bin/clang-21
+          CFLAGS=$CFLAGS
+          " > $GITHUB_ENV
+      - name: Install Deno
+        uses: denoland/setup-deno@v2
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        with:
+          deno-version: v2.x
+      - name: Install benchmark tools
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        env:
+          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
+        run: ./tools/install_prebuilt.js wrk hyperfine
+      - name: Build deno
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        run: cargo build --release -p deno
+      - name: Run benchmarks
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        run: cargo bench -p cli_tests --bench deno_bench --locked
+      - name: Post benchmarks
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'') && github.repository == ''denoland/deno'' && github.ref == ''refs/heads/main'''
+        env:
+          DENOBOT_PAT: '${{ secrets.DENOBOT_PAT }}'
+        run: |-
+          git clone --depth 1 --branch gh-pages                             \
+              https://${DENOBOT_PAT}@github.com/denoland/benchmark_data.git \
+              gh-pages
+          ./target/release/deno run --allow-all ./tools/build_benchmark_jsons.js --release
+          cd gh-pages
+          git config user.email "propelml@gmail.com"
+          git config user.name "denobot"
+          git add .
+          git commit --message "Update benchmarks"
+          git push origin gh-pages
+      - name: Worker info
+        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
+        run: |-
+          cat /proc/cpuinfo
+          cat /proc/meminfo
   build-debug-macos-x86_64:
     name: build debug macos-x86_64
     needs:
@@ -3402,102 +3567,6 @@ jobs:
         run: |-
           ./target/release/deno run --allow-all --lock=tools/deno.lock.json \
               ./tools/upload_wptfyi.js $(git rev-parse HEAD) --ghstatus
-  bench-release-linux-x86_64:
-    name: bench release linux-x86_64
-    needs:
-      - build-release-linux-x86_64
-    runs-on: '${{ github.repository == ''denoland/deno'' && ''ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04'' || ''ubuntu-24.04'' }}'
-    timeout-minutes: 240
-    defaults:
-      run:
-        shell: bash
-    env:
-      CARGO_TERM_COLOR: always
-      RUST_BACKTRACE: full
-      RUST_LIB_BACKTRACE: 0
-    steps:
-      - name: Configure git
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        run: |-
-          git config --global core.symlinks true
-          git config --global fetch.parallel 32
-      - name: Clone repository
-        uses: actions/checkout@v6
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        with:
-          fetch-depth: 5
-          submodules: false
-      - name: Install Node
-        uses: actions/setup-node@v6
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        with:
-          node-version: 22
-      - uses: dsherret/rust-toolchain-file@v1
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-      - name: Cache Cargo home
-        uses: cirruslabs/cache@v4
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        with:
-          path: |-
-            ~/.cargo/.crates.toml
-            ~/.cargo/.crates2.json
-            ~/.cargo/bin
-            ~/.cargo/registry/index
-            ~/.cargo/registry/cache
-            ~/.cargo/git/db
-          key: '94-cargo-home-linux-x86_64-${{ hashFiles(''Cargo.lock'') }}'
-          restore-keys: 94-cargo-home-linux-x86_64-
-      - name: Clone submodule ./tests/bench/testdata/lsp_benchdata
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        run: git submodule update --init --recursive --depth=1 -- ./tests/bench/testdata/lsp_benchdata
-      - name: Clone submodule ./tests/util/std
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        run: git submodule update --init --recursive --depth=1 -- ./tests/util/std
-      - name: Install Deno
-        uses: denoland/setup-deno@v2
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        with:
-          deno-version: v2.x
-      - name: Download artifact release-linux-x86_64-deno
-        uses: actions/download-artifact@v6
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        with:
-          name: release-linux-x86_64-deno
-          path: target/release
-      - name: Set target/release/deno permissions
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        run: chmod +x target/release/deno
-      - name: Install benchmark tools
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        env:
-          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
-        run: ./tools/install_prebuilt.js wrk hyperfine
-      - name: Build library for rlib file sizes
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        run: cargo build --release --lib -p deno
-      - name: Run benchmarks
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        run: cargo bench -p cli_tests --bench deno_bench --locked
-      - name: Post benchmarks
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'') && github.repository == ''denoland/deno'' && github.ref == ''refs/heads/main'''
-        env:
-          DENOBOT_PAT: '${{ secrets.DENOBOT_PAT }}'
-        run: |-
-          git clone --depth 1 --branch gh-pages                             \
-              https://${DENOBOT_PAT}@github.com/denoland/benchmark_data.git \
-              gh-pages
-          ./target/release/deno run --allow-all ./tools/build_benchmark_jsons.js --release
-          cd gh-pages
-          git config user.email "propelml@gmail.com"
-          git config user.name "denobot"
-          git add .
-          git commit --message "Update benchmarks"
-          git push origin gh-pages
-      - name: Worker info
-        if: '(contains(github.event.pull_request.labels.*.name, ''ci-bench'') || github.ref == ''refs/heads/main'') && !startsWith(github.ref, ''refs/tags/'')'
-        run: |-
-          cat /proc/cpuinfo
-          cat /proc/meminfo
   build-debug-linux-x86_64:
     name: build debug linux-x86_64
     needs:
