regenerate

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -179,14 +179,14 @@ jobs:
           sudo apt-get remove --purge -y man-db
 
           # Install clang-15, lld-15, and debootstrap.
-          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" |
-            sudo dd of=/etc/apt/sources.list.d/llvm-toolchain-focal-15.list
+          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main" |
+            sudo dd of=/etc/apt/sources.list.d/llvm-toolchain-jammy-15.list
           curl https://apt.llvm.org/llvm-snapshot.gpg.key |
             gpg --dearmor                                 |
           sudo dd of=/etc/apt/trusted.gpg.d/llvm-snapshot.gpg
           sudo apt-get update
           # this was unreliable sometimes, so try again if it fails
-          sudo apt-get install --no-install-recommends debootstrap clang-16 lld-16 || echo 'Failed. Trying again.' && sudo apt-get clean && sudo apt-get update && sudo apt-get install --no-install-recommends debootstrap clang-16 lld-16
+          sudo apt-get install --no-install-recommends debootstrap clang-15 lld-15 || echo 'Failed. Trying again.' && sudo apt-get clean && sudo apt-get update && sudo apt-get install --no-install-recommends debootstrap clang-15 lld-15
 
           # Create ubuntu-16.04 sysroot environment, which is used to avoid
           # depending on a very recent version of glibc.
@@ -194,14 +194,13 @@ jobs:
           # `file` and `make` are needed to build libffi-sys.
           # `curl` is needed to build rusty_v8.
           sudo debootstrap                                     \
-            --include=ca-certificates,curl,file,libc6,libc6-dev,make \
+            --include=ca-certificates,curl,file,libc6-dev,make \
             --no-merged-usr --variant=minbase xenial /sysroot  \
             http://azure.archive.ubuntu.com/ubuntu
           sudo mount --rbind /dev /sysroot/dev
           sudo mount --rbind /sys /sysroot/sys
           sudo mount --rbind /home /sysroot/home
           sudo mount -t proc /proc /sysroot/proc
-          sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /sysroot/usr/lib/libdl.so
 
           # Configure the build environment. Both Rust and Clang will produce
           # llvm bitcode only, so we can use lld's incremental LTO support.
@@ -215,7 +214,6 @@ jobs:
             -C linker=clang-15
             -C link-arg=-fuse-ld=lld-15
             -C link-arg=--sysroot=/sysroot
-            -C link-arg=-ldl
             -C link-arg=-Wl,--allow-shlib-undefined
             -C link-arg=-Wl,--thinlto-cache-dir=$(pwd)/target/release/lto-cache
             -C link-arg=-Wl,--thinlto-cache-policy,cache_size_bytes=700m
@@ -226,13 +224,12 @@ jobs:
             -C linker=clang-15
             -C link-arg=-fuse-ld=lld-15
             -C link-arg=--sysroot=/sysroot
-            -C link-arg=-ldl
             -C link-arg=-Wl,--allow-shlib-undefined
             -C link-arg=-Wl,--thinlto-cache-dir=$(pwd)/target/release/lto-cache
             -C link-arg=-Wl,--thinlto-cache-policy,cache_size_bytes=700m
             ${{ env.RUSTFLAGS }}
           __1
-          CC=clang-16
+          CC=clang-15
           CFLAGS=-flto=thin --sysroot=/sysroot
           __0
       - name: Log versions
