Try: link with lld-11

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,8 +40,9 @@ jobs:
       # e.g. a flaky test.
       # Don't fast-fail on tag build because publishing binaries shouldn't be
       # prevented if if any of the stages fails (which can be a false negative).
-      fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
-        'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')) }}
+      fail-fast: false
+      #fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
+      #  'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')) }}
 
     env:
       RUST_BACKTRACE: full
@@ -80,6 +81,26 @@ jobs:
         run: |
           rustup component add clippy
           rustup component add rustfmt
+
+      - name: Install clang-11 and lld-11 (Ubuntu 18.04)
+        if: matrix.os == 'ubuntu-18.04'
+        run: |
+          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key |\
+            sudo apt-key add -
+          sudo apt-add-repository -y \
+            'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
+          sudo apt update
+          sudo apt install -fy clang-11 lld-11
+
+      - name: Install clang-11 and lld-11 (Ubuntu 20.04)
+        if: startsWith(matrix.os, 'ubuntu-latest')
+        run: |
+          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key |\
+            sudo apt-key add -
+          sudo apt-add-repository -y \
+            'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
+          sudo apt update
+          sudo apt install -fy clang-11 lld-11
 
       - name: Install Deno
         if: |
@@ -174,8 +195,7 @@ jobs:
             ~/.cargo/git
             ~/.cargo/registry
             ./target
-          key:
-            b-${{ matrix.os }}-${{ matrix.kind }}-${{ hashFiles('Cargo.lock') }}
+          key: b-${{ matrix.os }}-${{ matrix.kind }}-${{ hashFiles('Cargo.lock') }}
           restore-keys: |
             b-${{ matrix.os }}-${{ matrix.kind }}-
 
